/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author bruno.azzi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.hideTabs();

        Post teste = new Post("","","","");
        teste.getPosts();
        System.out.println("teste: " + teste.getPosts());
        ArrayList<Post> posts = teste.getPosts();
        System.out.println("posts: " + posts.toString());
        
        for(int i = 0; i < posts.size(); i++) {
            JLabel[] jLabel = new JLabel[i];
            JTextArea[] jTextArea = new JTextArea[i];
            this.postTitle.setText(posts.get(i).title);
            this.postContent.setText(posts.get(i).content);
            
            JLabel label = new JLabel();
            label.setText("testeeeeee");
            this.loginPanel.add(label);
            System.out.println("label: " + label.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        welcomeText = new java.awt.Label();
        idLabel = new java.awt.Label();
        idInput = new java.awt.TextField();
        passwordInput = new java.awt.TextField();
        passwordLabel = new java.awt.Label();
        loginBtn = new javax.swing.JButton();
        loginMessage = new javax.swing.JLabel();
        forumPanel = new javax.swing.JPanel();
        postTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postContent = new javax.swing.JTextPane();
        createPostPanel = new javax.swing.JPanel();
        createPostBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        createPostContent = new javax.swing.JTextArea();
        createPostTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeText.setAlignment(java.awt.Label.CENTER);
        welcomeText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        welcomeText.setText("Bem Vindo ao Ceita Hacker");

        idLabel.setText("ID");

        passwordLabel.setText("Password");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmit(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(welcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(0, 227, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(227, 227, 227))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(308, 308, 308))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginMessage))
                                .addGap(282, 282, 282))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(welcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(loginMessage)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        mainPanel.addTab("Login", loginPanel);

        postTitle.setText("titulo do post");

        postContent.setBackground(new java.awt.Color(240, 240, 240));
        postContent.setBorder(null);
        postContent.setText("kasdndjasndnjnjsndsn jdns jndj sndjnsd njs dnjs djs njd njsndjsn djs njd nsjdnjs jd njs djnsj dnjs ndjsnjds n");
        postContent.setToolTipText("");
        jScrollPane2.setViewportView(postContent);

        javax.swing.GroupLayout forumPanelLayout = new javax.swing.GroupLayout(forumPanel);
        forumPanel.setLayout(forumPanelLayout);
        forumPanelLayout.setHorizontalGroup(
            forumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forumPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(forumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        forumPanelLayout.setVerticalGroup(
            forumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forumPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(postTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        mainPanel.addTab("Forum", forumPanel);

        createPostBtn.setText("Create Post");
        createPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewPost(evt);
            }
        });

        titleLabel.setText("Title");

        contentLabel.setText("Content");

        createPostContent.setColumns(20);
        createPostContent.setRows(5);
        createPostContent.setAlignmentX(1.0F);
        createPostContent.setAutoscrolls(false);
        jScrollPane1.setViewportView(createPostContent);

        javax.swing.GroupLayout createPostPanelLayout = new javax.swing.GroupLayout(createPostPanel);
        createPostPanel.setLayout(createPostPanelLayout);
        createPostPanelLayout.setHorizontalGroup(
            createPostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPostPanelLayout.createSequentialGroup()
                .addGroup(createPostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPostPanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(createPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createPostPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createPostPanelLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(contentLabel))
                    .addGroup(createPostPanelLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(titleLabel))
                    .addGroup(createPostPanelLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(createPostBtn)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        createPostPanelLayout.setVerticalGroup(
            createPostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPostPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(createPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(contentLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(createPostBtn)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mainPanel.addTab("Create Post", createPostPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewPost(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewPost
        Post newPost = new Post("nome", "data", this.createPostTitle.getText(), this.createPostContent.getText());
        System.out.println("newPost: " + newPost.toString());
        newPost.createPost(newPost);
    }//GEN-LAST:event_createNewPost

    private void loginSubmit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmit
        User loginData = new User(this.idInput.getText(), this.passwordInput.getText());
        this.clearLoginInputs();
        boolean loginIsAutenticated = loginData.validateLogin(loginData);
        this.loginMessage.setVisible(true);

        if (loginIsAutenticated == true) {
            this.loginMessage.setText("Logado como: " + loginData.id);
            this.showTabs();
        } else {
            this.loginMessage.setText("Usuário não encontrado");
            this.hideTabs();
        }

        System.out.println("loginData: " + loginData.toString());
        System.out.println("loginIsAutenticated: " + loginIsAutenticated);
    }//GEN-LAST:event_loginSubmit

    private void clearLoginInputs() {
        this.idInput.setText("");
        this.passwordInput.setText("");
    }
    
    private void hideTabs() {
        this.mainPanel.setEnabledAt(1, false);
        this.mainPanel.setEnabledAt(2, false);
    }
    
    private void showTabs() {
        this.mainPanel.setEnabledAt(1, true);
        this.mainPanel.setEnabledAt(2, true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contentLabel;
    private javax.swing.JButton createPostBtn;
    private javax.swing.JTextArea createPostContent;
    private javax.swing.JPanel createPostPanel;
    private javax.swing.JTextField createPostTitle;
    private javax.swing.JPanel forumPanel;
    private java.awt.TextField idInput;
    private java.awt.Label idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginMessage;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTabbedPane mainPanel;
    private java.awt.TextField passwordInput;
    private java.awt.Label passwordLabel;
    private javax.swing.JTextPane postContent;
    private javax.swing.JLabel postTitle;
    private javax.swing.JLabel titleLabel;
    private java.awt.Label welcomeText;
    // End of variables declaration//GEN-END:variables
}
